Algoritmo "e2"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
num1, num2: inteiro

Inicio
escreval("Digite um número inteiro")
leia(num1)
escreval("Digite mais um número inteiro")
leia(num2)

se num1 > num2 entao
escreval(num1 , " é o maior")
senao
se num2 > num1 entao
escreval(num2 , " é o maior")
senao
escreval("São iguais")
fimse
fimse

Fimalgoritmo